
<ul>
	<li>
		<strong>id:</strong>
		<span><?=CHtml::encode($model->id)?></span>
	</li>
	<li>
		<strong>comment_id:</strong>
		<span><?=CHtml::encode($model->comment_id)?></span>
	</li>
	<li>
		<strong>user_id:</strong>
		<span><?=CHtml::encode($model->user_id)?></span>
	</li>
	<li>
		<strong>value:</strong>
		<span><?=CHtml::encode($model->value)?></span>
	</li>
</ul>
