
<ul>
	<li>
		<strong>id:</strong>
		<span><?=CHtml::encode($model->id)?></span>
	</li>
	<li>
		<strong>user_id:</strong>
		<span><?=CHtml::encode($model->user_id)?></span>
	</li>
	<li>
		<strong>clan_id:</strong>
		<span><?=CHtml::encode($model->clan_id)?></span>
	</li>
	<li>
		<strong>rank_id:</strong>
		<span><?=CHtml::encode($model->rank_id)?></span>
	</li>
</ul>
