
<ul>
	<li>
		<strong>id:</strong>
		<span><?=CHtml::encode($model->id)?></span>
	</li>
	<li>
		<strong>parent_id:</strong>
		<span><?=CHtml::encode($model->parent_id)?></span>
	</li>
	<li>
		<strong>user_id:</strong>
		<span><?=CHtml::encode($model->user_id)?></span>
	</li>
	<li>
		<strong>name:</strong>
		<span><?=CHtml::encode($model->name)?></span>
	</li>
</ul>
