<?php

namespace Graphox;

require_once dirname(__FILE__) . '/../../../lib/Graphox/Crypto.php';

/**
 * Test class for Crypto.
 * Generated by PHPUnit on 2013-03-08 at 07:05:16.
 */
class CryptoTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Crypto
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Crypto;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers Graphox\Crypto::setUserPassword
	 * @todo Implement testSetUserPassword().
	 */
	public function testSetUserPassword()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::encodePassword
	 * @todo Implement testEncodePassword().
	 */
	public function testEncodePassword()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::checkUserPassword
	 * @todo Implement testCheckUserPassword().
	 */
	public function testCheckUserPassword()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::generateRandomKey
	 * @todo Implement testGenerateRandomKey().
	 */
	public function testGenerateRandomKey()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::init
	 * @todo Implement testInit().
	 */
	public function testInit()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::get_random_bytes
	 * @todo Implement testGet_random_bytes().
	 */
	public function testGet_random_bytes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::encode64
	 * @todo Implement testEncode64().
	 */
	public function testEncode64()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::gensalt_private
	 * @todo Implement testGensalt_private().
	 */
	public function testGensalt_private()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::crypt_private
	 * @todo Implement testCrypt_private().
	 */
	public function testCrypt_private()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::gensalt_extended
	 * @todo Implement testGensalt_extended().
	 */
	public function testGensalt_extended()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::gensalt_blowfish
	 * @todo Implement testGensalt_blowfish().
	 */
	public function testGensalt_blowfish()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::HashPassword
	 * @todo Implement testHashPassword().
	 */
	public function testHashPassword()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Graphox\Crypto::CheckPassword
	 * @todo Implement testCheckPassword().
	 */
	public function testCheckPassword()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
