
<ul>
	<li>
		<strong>id:</strong>
		<span><?=CHtml::encode($model->id)?></span>
	</li>
	<li>
		<strong>user_id:</strong>
		<span><?=CHtml::encode($model->user_id)?></span>
	</li>
	<li>
		<strong>page_id:</strong>
		<span><?=CHtml::encode($model->page_id)?></span>
	</li>
	<li>
		<strong>title:</strong>
		<span><?=CHtml::encode($model->title)?></span>
	</li>
	<li>
		<strong>content:</strong>
		<span><?=CHtml::encode($model->content)?></span>
	</li>
	<li>
		<strong>posted_date:</strong>
		<span><?=CHtml::encode($model->posted_date)?></span>
	</li>
</ul>
