
<ul>
	<li>
		<strong>id:</strong>
		<span><?=CHtml::encode($model->id)?></span>
	</li>
	<li>
		<strong>tag:</strong>
		<span><?=CHtml::encode($model->tag)?></span>
	</li>
	<li>
		<strong>clan_id:</strong>
		<span><?=CHtml::encode($model->clan_id)?></span>
	</li>
	<li>
		<strong>status:</strong>
		<span><?=CHtml::encode($model->status)?></span>
	</li>
</ul>
