
<ul>
	<li>
		<strong>id:</strong>
		<span><?=CHtml::encode($model->id)?></span>
	</li>
	<li>
		<strong>parent_id:</strong>
		<span><?=CHtml::encode($model->parent_id)?></span>
	</li>
	<li>
		<strong>name:</strong>
		<span><?=CHtml::encode($model->name)?></span>
	</li>
	<li>
		<strong>url:</strong>
		<span><?=CHtml::encode($model->url)?></span>
	</li>
	<li>
		<strong>acl_object_id:</strong>
		<span><?=CHtml::encode($model->acl_object_id)?></span>
	</li>
</ul>
